// <auto-generated />
namespace HospitalProject_Group3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class entities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(entities));
        
        string IMigrationMetadata.Id
        {
            get { return "202207050301456_entities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
